// Tab configuration for all Daily Intel verticals

export const TAB_CONFIGS = {
  finance: {
    key: "finance",
    label: "Finance",
    emoji: "📈",
    accentColor: "#b8921a",
    accentColorLight: "#c9a84c",
    accentDim: "rgba(184,146,26,0.10)",
    accentBadgeBg: "rgba(184,146,26,0.09)",
    pulseTitle: "MARKET PULSE",
    placeholder: "Search stories…",
    sources: "WSJ · Bloomberg · FT · CNBC · Reuters · MarketWatch · +more",
    rankingLabel: "Ranked by market importance",
    path: "/",
    metaTitle: "Daily Intel — Business & Investment News Digest",
    metaDescription: "World-class curated business and investment intelligence, delivered daily.",
  },
  health: {
    key: "health",
    label: "Health",
    emoji: "🌿",
    accentColor: "#059669",
    accentColorLight: "#10b981",
    accentDim: "rgba(5,150,105,0.08)",
    accentBadgeBg: "rgba(5,150,105,0.10)",
    pulseTitle: "HEALTH PULSE",
    placeholder: "Search health stories…",
    sources: "WSJ · NYT · Reuters Health · CNN Health · TIME · New Scientist · +more",
    rankingLabel: "Ranked by health relevance",
    path: "/health",
    metaTitle: "Health Intel — Daily Intel",
    metaDescription: "Daily health & wellness intelligence curated by AI.",
  },
  tech: {
    key: "tech",
    label: "Tech",
    emoji: "🤖",
    accentColor: "#3B82F6",
    accentColorLight: "#60A5FA",
    accentDim: "rgba(59,130,246,0.10)",
    accentBadgeBg: "rgba(59,130,246,0.09)",
    pulseTitle: "TECH PULSE",
    placeholder: "Search tech stories…",
    sources: "TechCrunch · Wired · The Verge · Ars Technica · MIT Tech Review · +more",
    rankingLabel: "Ranked by innovation impact",
    path: "/tech",
    metaTitle: "Tech Intel — Daily Intel",
    metaDescription: "Daily technology intelligence curated by AI.",
    defaultTopics: ["AI", "Software", "Hardware", "Chips", "Cloud", "Mobile", "Security", "Space", "Robotics", "Biotech"],
    imagePromptStyle: "Technology innovation editorial illustration, futuristic digital style",
  },
  geopolitics: {
    key: "geopolitics",
    label: "World",
    emoji: "🌍",
    accentColor: "#7C3AED",
    accentColorLight: "#A78BFA",
    accentDim: "rgba(124,58,237,0.10)",
    accentBadgeBg: "rgba(124,58,237,0.09)",
    pulseTitle: "WORLD PULSE",
    placeholder: "Search world stories…",
    sources: "Reuters · AP · FT · The Economist · Foreign Affairs · Al Jazeera · +more",
    rankingLabel: "Ranked by global impact",
    path: "/geopolitics",
    metaTitle: "World Intel — Daily Intel",
    metaDescription: "Daily geopolitical intelligence curated by AI.",
    defaultTopics: ["Diplomacy", "Trade", "Conflict", "Elections", "Sanctions", "NATO", "China", "Middle East", "Europe", "Americas"],
    imagePromptStyle: "International affairs editorial illustration, globe and diplomacy theme",
  },
  energy: {
    key: "energy",
    label: "Energy",
    emoji: "⚡",
    accentColor: "#D97706",
    accentColorLight: "#F59E0B",
    accentDim: "rgba(217,119,6,0.10)",
    accentBadgeBg: "rgba(217,119,6,0.09)",
    pulseTitle: "ENERGY PULSE",
    placeholder: "Search energy stories…",
    sources: "Reuters Energy · Bloomberg NEF · S&P Global · CNBC Energy · OilPrice · +more",
    rankingLabel: "Ranked by market impact",
    path: "/energy",
    metaTitle: "Energy Intel — Daily Intel",
    metaDescription: "Daily energy and commodities intelligence curated by AI.",
    defaultTopics: ["Oil", "Gas", "Renewables", "Nuclear", "Solar", "Wind", "Grid", "EV", "Climate", "OPEC"],
    imagePromptStyle: "Energy and power industry editorial illustration, clean modern style",
  },
  "real-estate": {
    key: "real-estate",
    label: "Real Estate",
    emoji: "🏠",
    accentColor: "#DC2626",
    accentColorLight: "#F87171",
    accentDim: "rgba(220,38,38,0.10)",
    accentBadgeBg: "rgba(220,38,38,0.09)",
    pulseTitle: "REAL ESTATE PULSE",
    placeholder: "Search real estate stories…",
    sources: "Bloomberg RE · CoStar · Globe St · Bisnow · CNBC RE · WSJ RE · +more",
    rankingLabel: "Ranked by market impact",
    path: "/real-estate",
    metaTitle: "Real Estate Intel — Daily Intel",
    metaDescription: "Daily real estate intelligence curated by AI.",
    defaultTopics: ["Residential", "Commercial", "REITs", "Mortgages", "Industrial", "Retail", "Multifamily", "Housing", "Office", "Data Centers"],
    imagePromptStyle: "Real estate and architecture editorial illustration, urban skyline style",
  },
  startups: {
    key: "startups",
    label: "Startups",
    emoji: "🚀",
    accentColor: "#0D9488",
    accentColorLight: "#14B8A6",
    accentDim: "rgba(13,148,136,0.10)",
    accentBadgeBg: "rgba(13,148,136,0.09)",
    pulseTitle: "DEAL PULSE",
    placeholder: "Search startup stories…",
    sources: "TechCrunch · Crunchbase · The Information · Bloomberg · PitchBook · +more",
    rankingLabel: "Ranked by deal significance",
    path: "/startups",
    metaTitle: "Startup Intel — Daily Intel",
    metaDescription: "Daily startup and venture capital intelligence curated by AI.",
    defaultTopics: ["Seed", "Series A", "Series B", "Growth", "IPO", "M&A", "AI", "Fintech", "Health", "Defense"],
    imagePromptStyle: "Startup and venture capital editorial illustration, rocket launch and innovation theme",
  },
  crypto: {
    key: "crypto",
    label: "Crypto",
    emoji: "₿",
    accentColor: "#F59E0B",
    accentColorLight: "#FBBF24",
    accentDim: "rgba(245,158,11,0.10)",
    accentBadgeBg: "rgba(245,158,11,0.09)",
    pulseTitle: "CRYPTO PULSE",
    placeholder: "Search crypto stories…",
    sources: "CoinDesk · The Block · Decrypt · Bloomberg Crypto · Reuters · +more",
    rankingLabel: "Ranked by market significance",
    path: "/crypto",
    metaTitle: "Crypto Intel — Daily Intel",
    metaDescription: "Daily crypto and blockchain intelligence curated by AI.",
    defaultTopics: ["Bitcoin", "Ethereum", "DeFi", "Regulation", "Mining", "Stablecoins", "Layer2", "Web3", "Institutional", "NFT"],
    imagePromptStyle: "Cryptocurrency and blockchain editorial illustration, digital finance theme",
  },
  science: {
    key: "science",
    label: "Science",
    emoji: "🔬",
    accentColor: "#06B6D4",
    accentColorLight: "#22D3EE",
    accentDim: "rgba(6,182,212,0.10)",
    accentBadgeBg: "rgba(6,182,212,0.09)",
    pulseTitle: "SCIENCE PULSE",
    placeholder: "Search science stories…",
    sources: "Nature · Science · New Scientist · ScienceDaily · Ars Technica · +more",
    rankingLabel: "Ranked by discovery significance",
    path: "/science",
    metaTitle: "Science Intel — Daily Intel",
    metaDescription: "Daily science and research intelligence curated by AI.",
    defaultTopics: ["Physics", "Biology", "Space", "Climate", "Neuroscience", "Chemistry", "Medicine", "AI Research", "Genetics", "Materials"],
    imagePromptStyle: "Scientific research editorial illustration, laboratory and discovery theme",
  },
  longevity: {
    key: "longevity",
    label: "Longevity",
    emoji: "🧬",
    accentColor: "#059669",
    accentColorLight: "#10B981",
    accentDim: "rgba(5,150,105,0.10)",
    accentBadgeBg: "rgba(5,150,105,0.09)",
    pulseTitle: "LONGEVITY PULSE",
    placeholder: "Search longevity stories…",
    sources: "Nature Aging · Longevity Technology · Life Extension · bioRxiv · +more",
    rankingLabel: "Ranked by longevity impact",
    path: "/longevity",
    metaTitle: "Longevity Intel — Daily Intel",
    metaDescription: "Daily longevity and aging research intelligence curated by AI.",
    defaultTopics: ["Senolytics", "NAD+", "Rapamycin", "Epigenetics", "Fasting", "Exercise", "Sleep", "Biomarkers", "Stem Cells", "Gene Therapy"],
    imagePromptStyle: "Longevity and anti-aging science editorial illustration, DNA and cellular health theme",
  },
  policy: {
    key: "policy",
    label: "Policy",
    emoji: "⚖️",
    accentColor: "#1E40AF",
    accentColorLight: "#3B82F6",
    accentDim: "rgba(30,64,175,0.10)",
    accentBadgeBg: "rgba(30,64,175,0.09)",
    pulseTitle: "POLICY PULSE",
    placeholder: "Search policy stories…",
    sources: "Reuters · Politico · The Hill · FT · WSJ · Bloomberg Law · +more",
    rankingLabel: "Ranked by regulatory impact",
    path: "/policy",
    metaTitle: "Policy Intel — Daily Intel",
    metaDescription: "Daily policy and regulatory intelligence curated by AI.",
    defaultTopics: ["Fed", "SEC", "FDA", "Treasury", "Trade", "Antitrust", "Climate", "Tech Regulation", "Healthcare", "Defense"],
    imagePromptStyle: "Government and policy editorial illustration, legislative and regulatory theme",
  },
  performance: {
    key: "performance",
    label: "Performance",
    emoji: "💪",
    accentColor: "#65A30D",
    accentColorLight: "#84CC16",
    accentDim: "rgba(101,163,13,0.10)",
    accentBadgeBg: "rgba(101,163,13,0.09)",
    pulseTitle: "PERFORMANCE PULSE",
    placeholder: "Search performance stories…",
    sources: "Men's Health · Outside · Runner's World · PubMed · Sports Science · +more",
    rankingLabel: "Ranked by performance impact",
    path: "/performance",
    metaTitle: "Performance Intel — Daily Intel",
    metaDescription: "Daily human performance intelligence curated by AI.",
    defaultTopics: ["Strength", "Endurance", "Recovery", "Nutrition", "Sleep", "Zone 2", "VO2 Max", "HRV", "Supplements", "Biomechanics"],
    imagePromptStyle: "Human athletic performance editorial illustration, fitness and sports science theme",
  },
};

// Ordered list for tab navigation
export const TAB_ORDER = [
  "finance", "health", "tech", "geopolitics", "energy",
  "real-estate", "startups", "crypto", "science", "longevity", "policy", "performance"
];

export const NEW_TABS = [
  "tech", "geopolitics", "energy", "real-estate", "startups",
  "crypto", "science", "longevity", "policy", "performance"
];
